# Variables and Types in Python

##Lists:


In [30]:
a=[1,2,3,4,5]
b=[1,'a', [1], "abjad"]

print(a)
print(b)

[1, 2, 3, 4, 5]
[1, 'a', [1], 'abjad']


In [33]:
print(a[4])

5


In [35]:
len(a)

5

In [38]:
c=[ [ 1, [2,33,"ab"], 4] , [4,5,6], [4,88] ]

print(c[1])     # [1,[2,33,'ab'],4].  -> [4,5,6]
print(c[0][1])  # [2,33,"ab" ]
print(c[0][1][2])  # "ab"
print(c[0][1][2][0] )  # a  

[4, 5, 6]
[2, 33, 'ab']
ab
a


In [39]:


for i in range(3):  # for i=1:3
  print( c[i])


[1, [2, 33, 'ab'], 4]
[4, 5, 6]
[4, 88]


for i=1:3


end

In [42]:
my_range= range(3)  # [1,2,3] [0,1,2]
print(my_range[0])
print(my_range[2])

0
2


In [50]:
dd= range(10,11)

print(dd[0])
print(dd[-1])


10
10


In [48]:
print(dd)


range(2, 11)


## Dictionaries:


In [56]:
a ={ "key": { "hossein":[3,4,5] , 1:54}, "athena": [6,8], 2: "Hossein" }

a["athena"]


[6, 8]

In [54]:
a[2]




'Hossein'

In [58]:
a["key"]

{1: 54, 'hossein': [3, 4, 5]}

4

##Arrays

In [2]:
import numpy as np



a= np.array([3,2,1])
print(a)

[3 2 1]


In [4]:
a.shape

(3,)

In [8]:
a.ndim

1

In [18]:
b=np.array( [ [1,2,3], [4,5,6], [7,8,9]])
print(b)
b.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [19]:
b.ndim

2

In Matlab we have array and Matrices.  But in Python we only have array
Arrays in python can have any dimentions. 
Dimention of arrays starts from 0, 1, 2, etc.

If you need to have a vector  in python you should define an array of size (1,3)

In [14]:
c=np.array([ [3], [2], [1]] )
print(c)

[[3]
 [2]
 [1]]


In [15]:
c.shape

(3, 1)

In [17]:
c.ndim

2

In [29]:
d=np.array( [[ [1, 1,4,5], [0,0,0,9] ],  [[2,3,0,0], [3,4,0,0]], [[2,5,0,0], [6,4,0,0]]   ])
print(d)
print(d.ndim)
print(d.shape)

[[[1 1 4 5]
  [0 0 0 9]]

 [[2 3 0 0]
  [3 4 0 0]]

 [[2 5 0 0]
  [6 4 0 0]]]
3
(3, 2, 4)
